# Generated by Django 3.1.4 on 2020-12-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
