# Generated by Django 3.1.4 on 2020-12-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_auto_20201231_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
