# Generated by Django 3.1.4 on 2020-12-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0003_auto_20201231_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={'ordering': ['id']},
        ),
    ]
