# Generated by Django 3.1.4 on 2021-01-01 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0004_auto_20201231_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateField(default=datetime.date(2021, 1, 1), verbose_name='Date created'),
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
