# Generated by Django 3.1.4 on 2021-01-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0009_auto_20210101_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
