# Generated by Django 3.1.4 on 2021-01-02 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0010_auto_20210101_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date created'),
        ),
    ]
